# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  
  # Configuracion comun
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.cpus = 1
  end


  # CAPA 1: Balanceador

  config.vm.define "balanceadorAlejandro" do |balancer|
    balancer.vm.hostname = "balanceadorAlejandro"
    # Interfaz hacia Internet/Cliente (DMZ)
    balancer.vm.network "private_network", ip: "192.168.10.10"
    # Interfaz hacia Backend
    balancer.vm.network "private_network", ip: "192.168.2.10"
    balancer.vm.network "forwarded_port", guest: 80, host: 8080
    balancer.vm.provision "shell", path: "provision/balanceador.sh"
    balancer.vm.provider "virtualbox" do |vb|
      vb.name = "balanceadorAlejandro"
    end
  end

  
  # CAPA 2: Servidor Web 1
  # Conexion con el balanceador 192.168.2.X
  # IP servidore webs 192.168.3.X
  
  config.vm.define "serverweb1Alejandro" do |web1|
    web1.vm.hostname = "serverweb1Alejandro"
    # Interfaz hacia Balanceador
    web1.vm.network "private_network", ip: "192.168.2.21"
    # Interfaz hacia NFS
    web1.vm.network "private_network", ip: "192.168.3.21"
    web1.vm.provision "shell", path: "provision/serverweb.sh"
    web1.vm.provider "virtualbox" do |vb|
      vb.name = "serverweb1Alejandro"
    end
  end


  # CAPA 2: Servidor Web 2
  # conexion con el balanceador 192.168.2.x
  # IP servidore webs: 192.168.3.x 
  
  config.vm.define "serverweb2Alejandro" do |web2|
    web2.vm.hostname = "serverweb2Alejandro"
    # Interfaz hacia Balanceador
    web2.vm.network "private_network", ip: "192.168.2.22"
    # Interfaz hacia NFS
    web2.vm.network "private_network", ip: "192.168.3.22"
    web2.vm.provision "shell", path: "provision/serverweb.sh"
    web2.vm.provider "virtualbox" do |vb|
      vb.name = "serverweb2Alejandro"
    end
  end



  # Conexion con el Servidor Web: 192.168.3.x
  # IP servidor nfs: 192.168.4.x 
 
  config.vm.define "serverNFSAlejandro" do |nfs|
    nfs.vm.hostname = "serverNFSAlejandro"
    # Interfaz hacia Servidores Web
    nfs.vm.network "private_network", ip: "192.168.3.23"
    # Interfaz hacia Proxy BD
    nfs.vm.network "private_network", ip: "192.168.4.23"
    nfs.vm.provision "shell", path: "provision/servernfs.sh"
    nfs.vm.provider "virtualbox" do |vb|
      vb.name = "serverNFSAlejandro"
      vb.memory = "768"
    end
  end

 
  # CAPA 3: Proxy BD
  # Conexion con el nfs: 192.168.4.x
  # IP Proxy BD: 192.168.5.x 
 
  config.vm.define "proxyBBDDAlejandro" do |proxy|
    proxy.vm.hostname = "proxyBBDDAlejandro"
    # Interfaz hacia NFS/Aplicacion
    proxy.vm.network "private_network", ip: "192.168.4.30"
    # Interfaz hacia Base de Datos
    proxy.vm.network "private_network", ip: "192.168.5.30"
    proxy.vm.provision "shell", path: "provision/proxybbdd.sh"
    proxy.vm.provider "virtualbox" do |vb|
      vb.name = "proxyBBDDAlejandro"
    end
  end


  # CAPA 4: Servidor de Base de Datos
  # Red BBDD: 192.168.5.x
 
  config.vm.define "serverdatosAlejandro" do |db|
    db.vm.hostname = "serverdatosAlejandro"
    # Interfaz hacia Proxy BB
    db.vm.network "private_network", ip: "192.168.5.40"
    db.vm.provision "shell", path: "provision/serverbbdd.sh"
    db.vm.provider "virtualbox" do |vb|
      vb.name = "serverdatosAlejandro"
      vb.memory = "768"
    end
  end
end